---
- name: Check for complaince and configure Standard configs
  hosts: pa-fw
  connection: local

  tasks:
    # - name: Check to see if device is ready
    #   paloaltonetworks.panos.panos_op:
    #     provider: '{{ provider }}'
    #     cmd: 'show chassis-ready'
    #   changed_when: false
    #   register: result
    #   until: result is not failed and (result.stdout | from_json).response.result == 'yes'
    #   retries: 50
    #   delay: 30

    - name: Get facts
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'
        gather_subset: ['all']
      register: device_data

    - name: Get facts
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'
        gather_subset: ['config']
      register: device_data_config

    - name: Get all virtual routers
      panos_virtual_router_facts:
        provider: '{{ provider }}'
      register: vrlist

    - name: Print data
      debug:
        msg: "{{ vrlist }}"

    - name: Retrieve address group object 'Prod'
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ provider }}'
      register: object_result

    - name: Print data
      debug:
        msg: "{{ object_result }}"

    - name: Print data
      debug:
        msg: "{{ device_data_config }}"
    # - name: Print Facts
    #   debug:
    #     msg: "{{ complete_facts }}"
            
    
    # - name: Get the system info
    #   paloaltonetworks.panos.panos_op:
    #     provider: "{{ provider }}"
    #     cmd: "show system info"
    #   register: res

    # - name: Get the system CPU info
    #   paloaltonetworks.panos.panos_op:
    #     provider: "{{ provider }}"
    #     cmd: "show system resources"
    #   register: res


    - name: Filter the value
      set_fact: 
        device_zone_config: "{{ device_data | ftr_zone }}"
        
    - name: validate the static route data against standards
      set_fact:
        missing_zone: "{{ standard_interfaces | validate_zone(device_zone_config) }}"

    - name: print
      debug:
        msg: "{{ missing_zone }}"

    # - name: Create Zones
    #   paloaltonetworks.panos.panos_zone:
    #     provider: "{{ provider }}"
    #     zone: "{{ zone_item.zone_name }}"
    #     mode: "{{ zone_item.mode }}"
    #   loop: "{{ missing_zone }}"
    #   loop_control:
    #     loop_var: zone_item
        
    # - name: Create Routes
    #   paloaltonetworks.panos.panos_static_route:
    #     provider: '{{ provider }}'
    #     name: '{{ route_item.name }}'
    #     destination: '{{ route_item.destination }}'
    #     nexthop: '{{ route_item.nexthop }}'
    #     interface: '{{ route_item.interface }}'
    #   loop: '{{ missing_routes }}'
    #   loop_control:
    #     loop_var: route_item
  
    # - name: 
    # - name: Create Address objects
    #   paloaltonetworks.panos.panos_address_object:
    #     provider: '{{ provider }}'
    #     name: '{{ address_item.name }}'
    #     value: '{{ address_item.value }}'
    #   loop: '{{ panos_address_object }}'
    #   loop_control:
    #     loop_var: address_item
    #   register: 
