---
- name: Check for complaince and configure Standard configs
  hosts: pa-fw
  connection: local
  vars_files:
    - standard_config.yml    

  tasks:
  
    # - name: Check to see if device is ready
    #   paloaltonetworks.panos.panos_op:
    #     provider: '{{ provider }}'
    #     cmd: 'show chassis-ready'
    #   changed_when: false
    #   register: result
    #   until: result is not failed and (result.stdout | from_json).response.result == 'yes'
    #   retries: 50
    #   delay: 30

    - name: Get  all facts
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'
        gather_subset: ['all']
      register: device_data
        
    - name: Create Virtual Router
      paloaltonetworks.panos.panos_virtual_router:
        provider: '{{ provider }}'
        state: gathered
      register: vrlist

    - name: Print virtual router data
      debug:
        msg: "{{ vrlist }}"
        
    - name: Parse the output
      set_fact:
       content_json: "{{ vrlist['gathered_xml'] | xml2json }}"

    - name: Print the static routes
      debug:
        msg: "{{ content_json }}"

    - name: Retrieve address group object all
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ provider }}'
        name_regex: '.*.*'
      register: object_result

    - name: Print object data
      debug:
        msg: "{{ object_result }}"

    - name: Retrieve address group object all
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ provider }}'
        name_regex: '.*.*'
        object_type: 'service'
      register: object_result

    - name: Print service only object data
      debug:
        msg: "{{ object_result }}"
        
    - name: Retrieve address group object all
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ provider }}'
        name_regex: '.*.*'
        object_type: 'service-group'
      register: object_result

    - name: Print service group object data
      debug:
        msg: "{{ object_result }}"
        
#Remove from here 
    # - name: Filter the value for Zones
    #   set_fact: 
    #     device_zone_config: "{{ device_data | ftr_zone }}"
        
    # - name: validate the device zones data against standards
    #   set_fact:
    #     missing_zone: "{{ standard_interfaces | validate_zone(device_zone_config) }}"

    # - name: Create Zones as per standards
    #   paloaltonetworks.panos.panos_zone:
    #     provider: "{{ provider }}"
    #     zone: "{{ zone_item.zone_name }}"
    #     mode: "{{ zone_item.mode }}"
    #   loop: "{{ missing_zone }}"
    #   loop_control:
    #     loop_var: zone_item

  #Remove till here 
  
    # - name: Create Routes
    #   paloaltonetworks.panos.panos_static_route:
    #     provider: '{{ provider }}'
    #     name: '{{ route_item.name }}'
    #     destination: '{{ route_item.destination }}'
    #     nexthop: '{{ route_item.nexthop }}'
    #     interface: '{{ route_item.interface }}'
    #   loop: '{{ missing_routes }}'
    #   loop_control:
    #     loop_var: route_item
  
    # - name: 
    # - name: Create Address objects
    #   paloaltonetworks.panos.panos_address_object:
    #     provider: '{{ provider }}'
    #     name: '{{ address_item.name }}'
    #     value: '{{ address_item.value }}'
    #   loop: '{{ panos_address_object }}'
    #   loop_control:
    #     loop_var: address_item
    #   register: 
