
panos_static_standard_route:
- name: outbound
  destination: '0.0.0.0/0'
  nexthop: '10.5.1.1'
  interface: 'ethernet1/1'
- name: to-web
  destination: '10.5.2.0/24'
  nexthop: '10.5.2.1'
  interface: 'ethernet1/2'
- name: to-database
  destination: '10.5.3.0/24'
  nexthop: '10.5.2.1'
  interface: 'ethernet1/2'
  
