
standard_interfaces:
- if_name: ethernet1/1
  zone_name: Untrust
  create_default_route: yes
  mode: 'layer3'
  commit: no
- if_name: ethernet1/2
  zone_name: Web
  create_default_route: no
  management_profile: Allow-HTTPS
  mode: 'layer3'
  commit: no
- if_name: ethernet1/3
  zone_name: DMZ
  create_default_route: no
  management_profile: Deny-all
  mode: 'layer3'
  commit: no

standard_address_object:
- name: web-object
  value: 10.5.2.5
- name: Database-objest
  value: 10.100.10.10

standard_service_object:
- name: service-tcp-22
  destination_port: 22
- name: service-tcp-221
  destination_port: 221
- name: service-tcp-222
  destination_port: 222
- name: service-tcp-3036
  destination_port: 3036

panos_security_rule:
- rule_name: 'URL deny for Azure'
  source_zone: 
  - Untrust
  source_ip: 
  - any
  destination_zone: 
  - Web
  destination_ip: 
  - any
  application: 
  - windows-azure
  service: 
  - service-http
  action: deny
