
standard_interfaces:
- if_name: ethernet1/1
  zone_name: Untrust
  create_default_route: yes
  mode: 'layer3'
  commit: no
- if_name: ethernet1/2
  zone_name: Web
  create_default_route: no
  management_profile: Allow-HTTPS
  mode: 'layer3'
  commit: no
- if_name: ethernet1/3
  zone_name: DMZ
  create_default_route: no
  management_profile: Deny-all
  mode: 'layer3'
  commit: no
